# Generated by Django 6.0.6 on 2026-06-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentprofile",
            name="certifications",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="education_details",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="extra_activities",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="internship_experience",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="resume_file",
        ),
        migrations.RemoveField(
            model_name="studentprofile",
            name="skills",
        ),
        migrations.AddField(
            model_name="job",
            name="max_backlogs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="min_cgpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="job",
            name="min_hsc_marks",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="job",
            name="min_ssc_marks",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="backlogs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="hsc_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="ssc_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "round_name",
                    models.CharField(
                        choices=[
                            ("Shortlist", "Shortlist"),
                            ("Technical", "Technical"),
                            ("HR", "HR"),
                            ("Final", "Final Selection"),
                        ],
                        default="Shortlist",
                        max_length=50,
                    ),
                ),
                ("meeting_details", models.TextField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("prep_checklist", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Confirmed", "Confirmed"),
                            ("Cancelled", "Cancelled"),
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                        ],
                        default="Confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="portal.recruiterprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("authority", models.CharField(max_length=255)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentInternship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("duration", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internships",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portal.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="InterviewSchedule",
        ),
    ]
