# Generated by Django 6.0.6 on 2026-06-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_remove_studentprofile_certifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumni",
            name="batch",
            field=models.CharField(
                blank=True, default="2026", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="alumni",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="alumni_images/"),
        ),
        migrations.AddField(
            model_name="alumni",
            name="linkedin",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="alumni",
            name="role",
            field=models.CharField(default="Software Engineer", max_length=255),
        ),
        migrations.AddField(
            model_name="alumni",
            name="testimonial",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="initials",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="alumni",
            name="year",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
