# Generated by Django 6.0.6 on 2026-06-24 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_alumni_batch_alumni_image_alumni_linkedin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interviews",
                to="portal.job",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="posted_by",
            field=models.CharField(
                choices=[("recruiter", "Recruiter"), ("admin", "Admin")],
                default="recruiter",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="portal.recruiterprofile",
            ),
        ),
    ]
