# Generated by Django 6.0.6 on 2026-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0004_interview_job_job_company_name_job_deadline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="preparation_checklist",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="preparation_checklist",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="job",
            name="source",
            field=models.CharField(
                choices=[("recruiter", "Recruiter"), ("admin", "Admin")],
                default="recruiter",
                max_length=20,
            ),
        ),
    ]
