# Generated by Django 6.0.6 on 2026-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0005_interview_preparation_checklist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="posted_by_type",
            field=models.CharField(
                choices=[("recruiter", "Recruiter"), ("admin", "Admin")],
                default="recruiter",
                max_length=20,
            ),
        ),
    ]
