# Generated by Django 6.0.6 on 2026-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0006_job_posted_by_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="gmail_app_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under Review", "Under Review"),
                    ("shortlisted", "shortlisted"),
                    ("technical_cleared", "technical_cleared"),
                    ("hr_cleared", "hr_cleared"),
                    ("hired", "hired"),
                    ("rejected", "rejected"),
                ],
                default="Under Review",
                max_length=50,
            ),
        ),
    ]
